### ISSUE TITLE
Does not display any device 

### ISSUE THREAD

**Issue by carlosnewmusic** [csicar/Ning#23] opened 2020-09-18 07:41 UTC
When you give it refresh, no remaining device appears like this 
![65d52d3d-45a3-46f6-917f-c522935354dc](https://user-images.githubusercontent.com/19379457/93570196-ede57200-f992-11ea-8af8-5225c2ebbe17.jpg)
It's Android 6.0.1

**Comment by csicar** [comment] 2020-09-18 08:34
Seems like there should be some exceptions thrown.

If you know how to Access the logs, it would be very useful if you could post them here.


If your device is rooted, you could use "LogCat Reader" from fdroid otherwise running adb logcat on your computer is probably the best way

More info can be found here https://android.stackexchange.com/questions/14430/how-can-i-view-and-examine-the-android-log

**Comment by dmitriy-ilchenko** [comment] 2020-09-18 20:47
I guess the app should show an error dialog if scanning failed.

**Comment by csicar** [comment] 2020-09-18 21:23
My current understanding is, that scanning can not fail. So I guess there must be a bug somewhere..

**Comment by csicar** [comment] 2021-09-05 12:19
seems to be a duplicate of https://github.com/csicar/Ning/issues/39

**Closed by csicar** 2021-09-05 12:19 UTC
Labels: bug
